### ISSUE TITLE
Not working on elcapitan

### ISSUE THREAD

**Issue by pavs** [dinamic/bw#2]
Tried it on elcapitan, changed interface from eth0 to en0 without any luck.

Tried to manually grep the output, I get result but not graph. Am I missing something obvious?

`netstat -ibnl | grep en0 | grep Link | awk '{print $7}'`

**Comment by pavs** [comment]
Worked on Linux though. Probably an issue on my side.

**Comment by dinamic** [comment]
Hey, sorry for the delay! I never realized there are issues opened for this repository.

**Comment by dinamic** [comment]
I can't confirm the problem, because I am running macOS Sierra now and it seems to be running fine.

![screen shot 2017-02-14 at 6 45 39 pm](https://cloud.githubusercontent.com/assets/11616/22938911/d617f61e-f2e5-11e6-8cdb-68fdda9c130c.png)

If you could give me some more information I will try to help you out.  Make sure you have selected the correct interface. You can find it using `ifconfig` and looking for `status: active`.

On my macbook the wifi is `en0`, while the thunderbolt ethernet adapter is `en4`. It may be different on your machine.

**Comment by dinamic** [comment]
ping @pavs

**Comment by dinamic** [comment]
I am closing this issue down. Please, reopen if you happen to experience it.
